import React, { useState, useEffect, useCallback } from 'react';
import {
  StyleSheet,
  View,
  Text,
  RefreshControl,
  Alert,
  SafeAreaView,
  ScrollView,
  TouchableOpacity
} from 'react-native';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import { apiService } from '../../services/api';
import Loading from '../../components/Loading';

export default function SalesReportScreen() {
  const [report, setReport] = useState(null);
  const [reportType, setReportType] = useState('DAILY'); // DAILY, WEEKLY, MONTHLY
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchReport = useCallback(async () => {
    try {
      const todayStr = new Date().toISOString().split('T')[0];
      let data;
      if (reportType === 'DAILY') {
        data = await apiService.sales.getDailyReport(todayStr);
      } else if (reportType === 'WEEKLY') {
        data = await apiService.sales.getWeeklyReport(todayStr);
      } else {
        data = await apiService.sales.getMonthlyReport(todayStr);
      }
      setReport(data);
    } catch (e) {
      console.error(e);
      Alert.alert('Report Error', 'Unable to retrieve sales report details.');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [reportType]);

  useEffect(() => {
    setLoading(true);
    fetchReport();
  }, [fetchReport]);

  const onRefresh = () => {
    setRefreshing(true);
    fetchReport();
  };

  if (loading && !refreshing) {
    return <Loading message="Generating report sheets..." fullScreen />;
  }

  return (
    <SafeAreaView style={styles.container}>
      {/* Tabs */}
      <View style={styles.tabBar}>
        <TouchableOpacity
          style={[styles.tab, reportType === 'DAILY' && styles.tabActive]}
          onPress={() => setReportType('DAILY')}
        >
          <Text style={[styles.tabText, reportType === 'DAILY' && styles.tabTextActive]}>Daily</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.tab, reportType === 'WEEKLY' && styles.tabActive]}
          onPress={() => setReportType('WEEKLY')}
        >
          <Text style={[styles.tabText, reportType === 'WEEKLY' && styles.tabTextActive]}>Weekly</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.tab, reportType === 'MONTHLY' && styles.tabActive]}
          onPress={() => setReportType('MONTHLY')}
        >
          <Text style={[styles.tabText, reportType === 'MONTHLY' && styles.tabTextActive]}>Monthly</Text>
        </TouchableOpacity>
      </View>

      <ScrollView
        contentContainerStyle={styles.scrollContent}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} color="#1976D2" />
        }
      >
        {/* Report Document Header */}
        <View style={styles.reportHeaderCard}>
          <Text style={styles.reportTitle}>{report?.title || 'DAWN BREAD - SALES REPORT'}</Text>
          <Text style={styles.reportRange}>Period: {report?.dateRange || 'N/A'}</Text>
          <Text style={styles.reportMeta}>Generated By: {report?.generatedBy || 'N/A'} | At: {report?.generatedAt ? `${new Date(report.generatedAt).toLocaleDateString()} ${new Date(report.generatedAt).toLocaleTimeString()}` : 'N/A'}</Text>
          
          <View style={styles.divider} />
          
          <View style={styles.statsSummaryRow}>
            <View style={styles.statsCell}>
              <Text style={styles.statsValue}>PKR {(report?.totalRevenue || 0).toLocaleString()}</Text>
              <Text style={styles.statsLabel}>Total Revenue</Text>
            </View>
            <View style={styles.statsCell}>
              <Text style={styles.statsValue}>{report?.totalUnits || 0}</Text>
              <Text style={styles.statsLabel}>Total Units Sold</Text>
            </View>
            <View style={styles.statsCell}>
              <Text style={styles.statsValue}>{report?.activeAgents || 0}</Text>
              <Text style={styles.statsLabel}>Agents Active</Text>
            </View>
          </View>
        </View>

        {/* Detailed Agent Breakdowns */}
        {reportType === 'DAILY' && (
          <>
            <Text style={styles.sectionTitle}>Agent Dispatches</Text>
            {report?.agentSummaries && report.agentSummaries.length > 0 ? (
              report.agentSummaries.map((summary, idx) => (
                <View key={idx} style={styles.agentCard}>
                  <View style={styles.agentHeader}>
                    <MaterialIcons name="person" size={20} color="#1976D2" />
                    <Text style={styles.agentName}>{summary.agentName} ({summary.employeeId})</Text>
                  </View>
                  <View style={styles.table}>
                    <View style={styles.tableHeaderRow}>
                      <Text style={[styles.tableHeaderCell, { flex: 2 }]}>Product</Text>
                      <Text style={[styles.tableHeaderCell, { flex: 0.6, textAlign: 'center' }]}>Qty</Text>
                      <Text style={[styles.tableHeaderCell, { flex: 1.2, textAlign: 'right' }]}>Unit Price</Text>
                      <Text style={[styles.tableHeaderCell, { flex: 1.2, textAlign: 'right' }]}>Total</Text>
                    </View>
                    {summary.items.map((item, itemIdx) => (
                      <View key={itemIdx} style={styles.tableBodyRow}>
                        <Text style={[styles.tableCell, { flex: 2, fontWeight: '500' }]} numberOfLines={1}>
                          {item.productName}
                        </Text>
                        <Text style={[styles.tableCell, { flex: 0.6, textAlign: 'center', fontWeight: 'bold' }]}>
                          {item.quantity}
                        </Text>
                        <Text style={[styles.tableCell, { flex: 1.2, textAlign: 'right', color: '#757575' }]}>
                          PKR {item.unitPrice}
                        </Text>
                        <Text style={[styles.tableCell, { flex: 1.2, textAlign: 'right', fontWeight: 'bold', color: '#2E7D32' }]}>
                          PKR {item.totalPrice}
                        </Text>
                      </View>
                    ))}
                  </View>
                  <View style={styles.agentFooterRow}>
                    <Text style={styles.agentFooterText}>Total Units: {summary.totalUnits}</Text>
                    <Text style={[styles.agentFooterText, { fontWeight: 'bold', color: '#1976D2' }]}>
                      Total Revenue: PKR {(summary.totalRevenue || 0).toLocaleString()}
                    </Text>
                  </View>
                </View>
              ))
            ) : (
              <View style={styles.emptyCard}>
                <Text style={styles.emptyText}>No agent dispatches submitted today.</Text>
              </View>
            )}
          </>
        )}

        {/* Product Performance ranking */}
        <View style={styles.sectionTitleRow}>
          <MaterialIcons name="trending-up" size={16} color="#424242" />
          <Text style={styles.sectionTitleWithIcon}>Top Selling Products</Text>
        </View>
        <View style={styles.rankingCard}>
          <View style={styles.tableHeaderRow}>
            <Text style={[styles.tableHeaderCell, { flex: 0.5 }]}>No</Text>
            <Text style={[styles.tableHeaderCell, { flex: 2 }]}>Product Name</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'center' }]}>Units</Text>
            <Text style={[styles.tableHeaderCell, { flex: 1.5, textAlign: 'right' }]}>Revenue</Text>
          </View>
          {report?.productPerformance && report.productPerformance.length > 0 ? (
            report.productPerformance.map((p, idx) => (
              <View key={idx} style={styles.tableBodyRow}>
                <Text style={[styles.tableCell, { flex: 0.5, color: '#757575', fontWeight: 'bold' }]}>{idx + 1}</Text>
                <Text style={[styles.tableCell, { flex: 2, fontWeight: '600' }]} numberOfLines={1}>{p.productName}</Text>
                <Text style={[styles.tableCell, { flex: 1, textAlign: 'center', fontWeight: 'bold' }]}>{p.quantitySold}</Text>
                <Text style={[styles.tableCell, { flex: 1.5, textAlign: 'right', fontWeight: 'bold', color: '#2E7D32' }]}>
                  PKR {(p.totalRevenue || 0).toLocaleString()}
                </Text>
              </View>
            ))
          ) : (
            <Text style={styles.emptyText}>No product performance data compiled.</Text>
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingVertical: 2
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent'
  },
  tabActive: {
    borderBottomColor: '#1976D2'
  },
  tabText: {
    fontSize: 14,
    color: '#757575',
    fontWeight: 'bold'
  },
  tabTextActive: {
    color: '#1976D2'
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 40
  },
  reportHeaderCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 }
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1A237E',
    textAlign: 'center'
  },
  reportRange: {
    fontSize: 12,
    color: '#333',
    textAlign: 'center',
    marginTop: 4,
    fontWeight: 'bold'
  },
  reportMeta: {
    fontSize: 10,
    color: '#757575',
    textAlign: 'center',
    marginTop: 4
  },
  divider: {
    height: 1,
    backgroundColor: '#EEEEEE',
    marginVertical: 12
  },
  statsSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-around'
  },
  statsCell: {
    alignItems: 'center',
    width: '30%'
  },
  statsValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#212121'
  },
  statsLabel: {
    fontSize: 10,
    color: '#757575',
    marginTop: 2
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#424242',
    marginTop: 18,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5
  },
  sectionTitleWithIcon: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#424242',
    marginLeft: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5
  },
  agentCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    padding: 12,
    marginBottom: 12,
    elevation: 2
  },
  agentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 8,
    marginBottom: 8
  },
  agentName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#212121',
    marginLeft: 6
  },
  table: {
    width: '100%'
  },
  tableHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
    paddingBottom: 4
  },
  tableHeaderCell: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#757575',
    textTransform: 'uppercase'
  },
  tableBodyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5'
  },
  tableCell: {
    fontSize: 12,
    color: '#333'
  },
  agentFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE'
  },
  agentFooterText: {
    fontSize: 12,
    color: '#555'
  },
  emptyCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EEEEEE'
  },
  emptyText: {
    color: '#757575',
    fontSize: 12
  },
  rankingCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    padding: 12,
    elevation: 2
  }
});
