-- Super Admin (Option B): fully separate identity from Agent/tenant data.
-- No tenant_id — a super admin does not belong to any single tenant.
-- No company_code login — authenticates via its own dedicated endpoint.
CREATE TABLE super_admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE UNIQUE INDEX ux_super_admins_username ON super_admins (UPPER(username));
CREATE UNIQUE INDEX ux_super_admins_email ON super_admins (UPPER(email));
