-- LMT (Customer Master Data) Stage 1: purely additive new tables — nothing
-- existing (agent, mart, sales_records, sale_items, attendance) is touched,
-- altered, or read/written by this migration. No new column on any live
-- table, no lock contention with the 25 agents' daily check-in/sale writes.
-- Nothing yet references these tables, so this stage has zero runtime
-- effect until the admin CRUD controllers built alongside it are called.

CREATE TABLE hierarchy_persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    role_label VARCHAR(50),
    contact VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6)
);

CREATE TABLE areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    tse_id BIGINT REFERENCES hierarchy_persons(id),
    sr_tse_id BIGINT REFERENCES hierarchy_persons(id),
    asm_id BIGINT REFERENCES hierarchy_persons(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6)
);

CREATE UNIQUE INDEX ux_areas_tenant_name ON areas (tenant_id, name);

CREATE TABLE customer_shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    shop_code VARCHAR(50) NOT NULL,
    shop_name VARCHAR(255) NOT NULL,
    branch VARCHAR(255),
    address VARCHAR(500),
    phone VARCHAR(50),
    mobile VARCHAR(50),
    email VARCHAR(255),
    strn VARCHAR(50),
    ntn VARCHAR(50),
    area_id BIGINT NOT NULL REFERENCES areas(id),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    radius DOUBLE PRECISION,
    geo_fencing_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6)
);

CREATE UNIQUE INDEX ux_customer_shops_tenant_shop_code ON customer_shops (tenant_id, shop_code);

-- One row per tenant. geofence_buffer_meters is read by a later stage's
-- shop-visit hard-gate (shop.radius + this buffer) — attendance check-in's
-- existing hard block against Mart.radius does not read this table.
CREATE TABLE lmt_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    geofence_buffer_meters DOUBLE PRECISION NOT NULL DEFAULT 50.0,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE UNIQUE INDEX ux_lmt_settings_tenant ON lmt_settings (tenant_id);

-- Seed a default settings row for every existing tenant (same seeding
-- approach as V10) so the service layer never has to special-case "no row
-- yet" for a tenant that already existed before this migration ran.
INSERT INTO lmt_settings (tenant_id, geofence_buffer_meters, created_at, updated_at)
SELECT id, 50.0, now(), now() FROM tenants;
