-- Phase C (stock reconciliation): two brand-new tables, no ALTER on any
-- existing table (agent, attendance, sale_items, sales_records, mart all
-- untouched). Zero risk to the 25 live Agents or any existing LMT data.

CREATE TABLE lmt_daily_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL REFERENCES agent(id),
    stock_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMP,
    reconciled_at TIMESTAMP
);

-- One stock day per LMT — mirrors the @UniqueConstraint on LmtDailyStock so
-- prod (this file) and the test suite (Hibernate DDL from annotations,
-- Flyway disabled there) describe the identical physical shape, same
-- lesson as V19's sale_items index.
CREATE UNIQUE INDEX ux_lmt_daily_stock_agent_date
    ON lmt_daily_stock (agent_id, stock_date);

CREATE TABLE lmt_daily_stock_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    lmt_daily_stock_id BIGINT NOT NULL REFERENCES lmt_daily_stock(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    opening_stock INTEGER NOT NULL DEFAULT 0,
    returned_qty INTEGER NOT NULL DEFAULT 0,
    unsold_qty INTEGER NOT NULL DEFAULT 0,
    sold_qty INTEGER NOT NULL DEFAULT 0,
    missing_qty INTEGER NOT NULL DEFAULT 0
);

-- One row per product per day — mirrors LmtDailyStockItem's
-- @UniqueConstraint, same reasoning as above.
CREATE UNIQUE INDEX ux_lmt_daily_stock_item_stock_product
    ON lmt_daily_stock_item (lmt_daily_stock_id, product_id);
