-- Per-shop discounts (Feature 2, P4): additive only, no existing column
-- altered or dropped. Applies to LMT shop-visit SALE lines only (see
-- SalesService.submitShopVisit, P5) — never touches the legacy Agent
-- sales flow, which has no shop or discount concept at all.

-- Overall discount % for a shop — null/0 means "no shop-level discount".
ALTER TABLE customer_shops ADD COLUMN discount_percent DOUBLE PRECISION;

-- Per-shop, per-product override: if a row exists here for a given
-- (shop, product), it wins over the shop's overall discount_percent for
-- that product. One row per (shop, product) pair.
CREATE TABLE shop_product_discount (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_shop_id BIGINT NOT NULL REFERENCES customer_shops(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    discount_percent DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX ux_shop_product_discount_shop_product
    ON shop_product_discount (customer_shop_id, product_id);

-- Records what discount (if any) applied to this line at submission time
-- — auditable per line, forever, same as unit_price/total_price already
-- are. Null/0 for every row that isn't an LMT SALE line (legacy Agent
-- rows, RETURN, UNSOLD) — RETURN/UNSOLD are never discounted (see
-- SalesService.submitShopVisit, P5).
ALTER TABLE sale_items ADD COLUMN discount_percent DOUBLE PRECISION;
