-- Per-shop-per-product prices (additive only): an explicit price the admin
-- sets for one product at one shop. Used ONLY by salesman (LMT/local)
-- shop-visit sales — SalesService.submitShopVisit resolves the base price
-- as: this row's price if one exists, else products.salesman_price. The
-- shop discount % is then applied on top of that base price. The Agent
-- sales flow never reads this table (agents always use agent_price).
--
-- No row for a (shop, product) pair means "fall back to the global
-- salesman price" — admins only add rows for products that differ.
-- Existing sale_items rows are untouched: unit_price/total_price were
-- written once at submission time and are never recomputed.

CREATE TABLE shop_product_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_shop_id BIGINT NOT NULL REFERENCES customer_shops(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    price DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX ux_shop_product_price_shop_product
    ON shop_product_price (customer_shop_id, product_id);
