-- QR shop-visit flow (Stage Q1): per-shop QR requirement, tenant-wide
-- master-override switches for geofence/QR enforcement, and the
-- scan-attempt log itself (created on every scan, pass or fail).
--
-- Fully additive: no existing column is altered or dropped, and both new
-- lmt_settings columns default to 'PER_SHOP' — meaning "respect each
-- shop's own setting, exactly as today" — so no existing shop's behavior
-- changes until an admin deliberately picks FORCE_ON/FORCE_OFF. qr_required
-- defaults to false on every existing shop, so QR is opt-in per shop.

ALTER TABLE customer_shops ADD COLUMN qr_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE lmt_settings ADD COLUMN geofence_mode VARCHAR(20) NOT NULL DEFAULT 'PER_SHOP';
ALTER TABLE lmt_settings ADD COLUMN qr_mode VARCHAR(20) NOT NULL DEFAULT 'PER_SHOP';

-- customer_shop_id is nullable: a scan of an unregistered/invalid code
-- still gets logged (for the admin's failed-scan visibility) but has no
-- shop to link to.
CREATE TABLE shop_visit_scan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL REFERENCES agent(id),
    customer_shop_id BIGINT REFERENCES customer_shops(id),
    scanned_code VARCHAR(100) NOT NULL,
    scan_date DATE NOT NULL,
    scan_time TIME NOT NULL,
    gps_latitude DOUBLE PRECISION NOT NULL,
    gps_longitude DOUBLE PRECISION NOT NULL,
    distance_from_shop_meters DOUBLE PRECISION,
    geofence_status VARCHAR(20) NOT NULL,
    visit_status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP
);

-- Backs both the QR-required enforcement check in SalesService
-- (agent + shop + today) and the admin's per-salesman-per-day views (Q2).
CREATE INDEX ix_shop_visit_scan_agent_shop_date
    ON shop_visit_scan (agent_id, customer_shop_id, scan_date);
